services:
  database:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=test'
      - 'POSTGRES_DB=test'
      - 'POSTGRES_PASSWORD=test'
    volumes:
      - './volumes/sweetpeakdesign/postgres:/var/lib/postgresql/data'